import { fontDataFor } from "@retorika/publisher";
import { SHIPPABLE_FAMILIES } from "@retorika/renderer";

/**
 * One shipped face, by its file name, so that **the preview is set in the letter the ZIP ships.**
 *
 * **The editor's canvas had been lying about the typeface since sprint 11, and it was measured on
 * sprint 13 day 7.** `packages/renderer/src/fonts.ts` emits `@font-face` with `url("fonts/<file>")`
 * — relative, which is right for the ZIP and right for `file://`. The canvas is an `<iframe srcDoc>`,
 * so a relative URL there resolves against *the editor's* origin, where nothing answered: eight
 * requests per render, all 404, and the page fell back to the stack. So the owner chose «Clásica y
 * seria», edited in Georgia, and downloaded Playfair Display. The one thing a preview is for is being
 * what you are going to get.
 *
 * Serving them here fixes it with **no change to the renderer at all**, which is why this route
 * exists rather than an option threaded through `render`: the URL is already the URL this answers.
 *
 * **A route rather than files in `public/`, and that is the decision rather than the easier path.**
 * The bytes live base64 in `packages/publisher/src/fontData.ts`, generated by
 * `scripts/generate-font-data.ts` and compared against what `@fontsource` ships by
 * `packages/publisher/test/fonts.test.ts`. Copying four `.woff2` files into `public/fonts/` would be a
 * **second copy of the same bytes**, with nothing holding the two level — the exact drift that file's
 * own comment exists to prevent. One source, read twice.
 *
 * **The file name is never a path**, which is the property the sibling `api/muestras/[id]` route
 * protects for photographs and `fonts.ts` protects for the published page — «a document may *choose* a
 * row from this table and can never *name* a file». The closed list below is **derived from that same
 * table**, so it cannot drift from what a page may ask for, and a segment shaped like
 * `../../../etc/passwd` is simply a name nothing matches: a 404, not a traversal. Nothing is joined to
 * a path anywhere in this file.
 *
 * `runtime = "nodejs"`: `fontDataFor` decodes with `Buffer`.
 */
export const runtime = "nodejs";

/**
 * Every face a published page may name, from the renderer's own table.
 *
 * Built once at module load, and **a `Set` rather than a scan** because this is asked for on every
 * render of every preview. Four entries today — two families, two weights each.
 */
const SERVABLE: ReadonlySet<string> = new Set(
  SHIPPABLE_FAMILIES.flatMap((family) => family.faces.map((face) => face.file)),
);

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ file: string }> },
): Promise<Response> {
  const { file } = await params;

  // Asked of the table before the bytes, so a name no page could ever emit is a plain 404 rather
  // than a lookup in a map keyed by something else. It is a public endpoint and "no such face" is an
  // ordinary answer to an ordinary mistake.
  if (!SERVABLE.has(file)) return new Response("not found", { status: 404 });

  const bytes = fontDataFor(file);
  if (!bytes) {
    // The renderer's table names it and the publisher has no bytes for it. The request was fine and
    // the bundle is not — the same split the photo route makes, and the same reason for a 500: a
    // `fonts.test.ts` that holds the two level has stopped holding.
    return new Response("shipped face is missing its bytes", { status: 500 });
  }

  // Copied into a fresh, concrete `ArrayBuffer`: `Buffer`'s `Uint8Array` is typed over the generic
  // `ArrayBufferLike`, which `BodyInit` does not accept. The same step, for the same reason, that
  // the photo route and the download route each take and each say so.
  const body = new ArrayBuffer(bytes.byteLength);
  new Uint8Array(body).set(bytes);

  return new Response(body, {
    status: 200,
    headers: {
      "Content-Type": "font/woff2",
      "Content-Length": String(bytes.byteLength),
      // Immutable, and that is a fact about the file rather than a hope: the name carries the family,
      // the subset, the weight and the style, and the OFL only lets Playfair Display's reserved name
      // travel with an *unmodified* face — so a changed face would be a changed name. Worth caching
      // hard: the canvas asks for these on every reload, and every edit is a reload.
      "Cache-Control": "public, max-age=31536000, immutable",
    },
  });
}
