import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { FONT_SOURCES } from "../packages/publisher/src/fonts.ts";

/**
 * Writes `packages/publisher/src/fontData.ts`: the shipped faces and their licences, as base64.
 *
 * **Why the bytes live in source rather than being read from `node_modules` at run time.** Three
 * attempts at reading them failed in the one place that matters — the download route, inside Next's
 * bundled server runtime — while every unit test passed:
 *
 *   1. `import.meta.resolve` → "is not a function" in that runtime.
 *   2. a dynamic `require.resolve` → "Cannot find module as expression is too dynamic".
 *   3. literal `require.resolve` of each `package.json` → Turbopack rewrote the resolved path to the
 *      placeholder `[project]/node_modules/...`, and the read then failed with ENOENT.
 *
 * The pattern is that a bundler treats module resolution as its own business, so the way to be certain
 * is to have nothing to resolve and no path to read. Base64 in a generated module is bundler-proof, is
 * deterministic, and keeps `@retorika/publisher` with no third-party **runtime** dependency at all —
 * which its own package comment has prized since it was written.
 *
 * It also makes condition 3 of this sprint checkable rather than asserted: `fonts.test.ts` compares the
 * decoded bytes against the package's files, so "exactly as `@fontsource` ships them" is a test and not
 * a promise. Run `pnpm fonts:generate` after changing a pinned version.
 */

const require_ = createRequire(import.meta.url);
const packageDir = (name: string) => dirname(require_.resolve(`${name}/package.json`));

const entries: string[] = [];
const seenLicences = new Set<string>();

for (const [name, source] of Object.entries(FONT_SOURCES)) {
  const dir = packageDir(source.package);
  const face = readFileSync(join(dir, "files", source.file));
  entries.push(`  "${name}": "${face.toString("base64")}",`);
  if (!seenLicences.has(source.licencePath)) {
    seenLicences.add(source.licencePath);
    const licence = readFileSync(join(dir, "LICENSE"));
    entries.push(`  "${source.licencePath}": "${licence.toString("base64")}",`);
  }
}

const file = `// GENERATED by scripts/generate-font-data.ts — do not edit by hand.
//
// The shipped faces and their licence texts, base64-encoded, keyed exactly as
// \`BuildSiteOptions.fonts\` wants them: a face by its file name, a licence by the path it takes in the
// bundle.
//
// **In source rather than read from disk at run time**, because three different ways of resolving them
// from \`node_modules\` each worked in tests and failed inside Next's bundled server runtime. The
// generator's own comment records all three. \`packages/publisher/test/fonts.test.ts\` compares these
// bytes against the package's files, so this file cannot drift from what \`@fontsource\` ships.
//
// Regenerate with \`pnpm fonts:generate\`.

/** biome-ignore-all lint/style/useNamingConvention: these keys are file names, not identifiers. */
const BASE64: Readonly<Record<string, string>> = {
${entries.join("\n")}
};

/** The bytes for one entry, or \`undefined\` when this product ships no such file. */
export function fontDataFor(key: string): Uint8Array | undefined {
  const encoded = BASE64[key];
  return encoded === undefined ? undefined : Uint8Array.from(Buffer.from(encoded, "base64"));
}

/** Every key this module carries, for the test that holds it level with \`FONT_SOURCES\`. */
export const FONT_DATA_KEYS: readonly string[] = Object.keys(BASE64);
`;

const out = join(import.meta.dirname, "..", "packages", "publisher", "src", "fontData.ts");
writeFileSync(out, file);
console.log(
  `generate-font-data: wrote ${entries.length} entries, ${(file.length / 1024).toFixed(1)} KB`,
);
